Islandora-Devops/islandora-starter-site

- composer.json
- composer.lock
Includes pdf.js in the starter site.
This will make the pdf.js library available [edited to say: as part of the starter-site]. Currently when you create an ISLE site that uses the Starter Site, pdf.js is not available. The Playbook does currently install pdf.js on its own, so a PR will follow to remove that.
* **Related GitHub Issue**: Reported by @nigelgbanks 
* **Other Relevant Links**: (Google Groups discussion, related pull requests,
Release pull requests, etc.)
* List pdf.js as a package, similar to [the install profile](https://github.com/Islandora-Devops/islandora_install_profile_demo/blob/e20dd33b6a09344620c65ab7104cb4a16c4ca55d/composer.json#L54-L65). 
* Require it.
* Does this change add any new dependencies? **yes, it adds one that was missing!**
* Does this change require any …
> Include pdf.js library.

- config/sync/block.block.creatorsandcontributors.yml
- config/sync/block.block.exposedformsolr_search_contentpage_1.yml
- config/sync/block.block.physicalform.yml
- config/sync/block.block.subject.yml
- config/sync/block.block.subjectname.yml
- config/sync/block.block.temporalsubject.yml
- config/sync/facets.facet.creators_and_contributors.yml
Switches facet and search blocks in the Bartik theme to the Olivero theme. Fixes some of the block displays and makes the search bar available for use.
* **Related GitHub Issue**: https://github.com/Islandora/islandora-starter-site/issues/10
https://github.com/Islandora/islandora-starter-site/issues/23
* **Other Relevant Links**: (Google Groups discussion, related pull requests,
Release pull requests, etc.)
* Changes facets in Bartik to Olivero and places them in the sidebar region.
* Changes  solr search content block from Bartik to Olivero.
* Does this change add any new dependencies?  No
* Does this change require any other modifications to be made to the repository
(i.e. Regeneration activity, etc.)?  No
* Could this change impact execution of existing code? No
* If using isle-dc, …
> Bartik to Olivero Facet and Search Blocks

- config/sync/core.extension.yml
- config/sync/devel.settings.yml
- config/sync/devel.toolbar.settings.yml
- config/sync/field.storage.node.field_weight.yml
- config/sync/system.menu.devel.yml
- config/sync/views.view.manage_members.yml
* Install the devel module (very useful to have if you're creating a site. Turn off on production) 
* Give the field_weight an index in the database (see https://github.com/Islandora/islandora/pull/924) 
* Use the field_weight to order the children in the List Children view (see https://github.com/Islandora/islandora/pull/900)
> Devel, field_weight index and sorting.

- README.md
1 - I want this README to make clear that we provide a template and no updates. It'll be documented in other places too, but including it in the README seems responsible.
2 - Changes to the install instructions. Most changes are superficial. Meaningful changes include:
* mentioning Solr as a prerequisite
* instead of telling users they need to install the prerequisites in a certain location, the instructions now include a step where you set the configs to point to the prerequisites, wherever you set them up at. It lists the configs in a table. I think this is more in the spirit of the starter site. I also mention config overrides, which is honestly probably a idea for site admins to know about and use in situations like this.
With my gratitude for the install instructions by @adam-vessey
> Add "what is a starter site" and config-set step

- composer.json
- composer.lock
- config/sync/core.extension.yml
This PR installs the Term Merge Drupal module. It's purpose is to allow site administrators to normalize terms that are duplicated.   
Composer.json Changes
"drupal/term_merge": "^2.0@beta",
"minimum-stability": "dev",
I had to change the minimum stability because I was getting this error: 
- drupal/term_merge[2.0.0-beta1, ..., 2.0.0-beta4] require drupal/term_reference_change * -> found drupal/term_reference_change[dev-1.x, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0 beta1, 1.x-dev (alias of dev-1.x)] but it does not match your minimum-stability. 
- Root composer.json requires drupal/term_merge ^2.0@beta -> satisfiable by drupal/term_merge[2.0.0-beta1, 2.0.0-beta2, 2.0.0-beta3, 2.0.0-beta4].
Composer.lock Changes
Module | Version
-- | -- |
drupal/term_merge | 2.0.0-beta4 | …
> Term merge module

- config/sync/field.field.node.islandora_object.field_linked_agent.yml
The Linked Agent field doesn't let you create terms on the fly.
This adds some helpful links in the field's help text so that you can add new people, corporate bodies, and families.
> Add links to make new terms to linked agent field help text.

- .gitattributes
- config/sync/core.entity_form_display.node.islandora_object.default.yml
- config/sync/core.entity_form_display.taxonomy_term.corporate_body.default.yml
- config/sync/core.entity_form_display.taxonomy_term.family.default.yml
- config/sync/core.entity_form_display.taxonomy_term.person.default.yml
- config/sync/field.field.node.islandora_object.field_linked_agent.yml
- config/sync/field.field.taxonomy_term.corporate_body.field_relationships.yml
- config/sync/field.field.taxonomy_term.family.field_relationships.yml
- config/sync/field.field.taxonomy_term.person.field_relationships.yml
- config/sync/field.storage.node.field_copyright_date.yml
- config/sync/field.storage.node.field_date_captured.yml
- config/sync/field.storage.node.field_date_modified.yml
- config/sync/field.storage.node.field_date_valid.yml
- config/sync/field.storage.node.field_edtf_date.yml
- config/sync/field.storage.node.field_edtf_date_created.yml
- config/sync/field.storage.node.field_edtf_date_issued.yml
- config/sync/field.storage.taxonomy_term.field_cat_date_begin.yml
- config/sync/field.storage.taxonomy_term.field_cat_date_end.yml
- config/sync/rest_oai_pmh.settings.yml
- config/sync/views.view.newspapers.yml
This brings the starter site in line with what you get when you export the unchanged config from a loaded starter site. Nothing has changed except that the configs now export slightly differently.
* I'm not sure why `linguist-language` snuck in there but it seems to happen both on ISLE and Playbook, so I'm including it.
* A lot of the other changes seem to have to do with improvements to the use of Schemas. e.g. numbers are stored as integers, booleans are stored as boolean.
> Trivial config updates including reordering yml.

- config/sync/views.view.media.yml
This addresses #34 .
Previously, the "orphaned" filter found items where media_of was not set.
However, the most likely "orphan" case is when a node is deleted, and then media_of remains set but does not link to a real node.
This new filter for "Orphans" finds both:
* media with no media_of
* media where media_of is internally set to a non-existent node.
I've had a bit of trouble trying to get the nid of the deleted node to display transparently to the user. This is really difficult! Drupal does a lot of work to hide from you the fact that there is a referenced entity which does not exist.
Nonetheless, this change addresses "Finding orphans" which are being missed by the current view.
> Fix orphaned media view filter.

- composer.json
- composer.lock
Addresses https://github.com/Islandora-Devops/islandora-starter-site/issues/64
We've added Views Nested Details to Packagist, and it's auto-updating. We can now remove the repository and the lock to one specific version. 
The composer.json file includes a carat operator so any 1.x release (including betas) will be considered compatible.
> Update to use packagist for views_nested_details.

- README.md
- assets/templates/mods.html.twig
- composer.json
- composer.lock
- config/sync/context.context.citation_select_block.yml
- config/sync/context.context.display_oai_pmh_item_links.yml
- config/sync/rest_oai_pmh.settings.yml
- config/sync/search_api.index.default_solr_index.yml
- config/sync/views.view.oai_pmh_item_data.yml
- config/sync/views.view.oai_pmh_item_links.yml
This PR provides a MODS representation.  This is done by powering a twig powered OAI-PMH Record view powered by a Drupal view consisting of a given Repository Item metadata.
Composer Changes
* places a MODS template (mods.html.twig) via post-update-cmd
Config Changes
* rest_oai_pmh.settings - module config, sets up MODS
* views.view.oai_pmh_item_data - provides the metadata that powers the twig 
* search_api.index.default_solr_index - some additional fields such as the ID needed for the above view
* views.view.oai_pmh_item_links - sets up the block needed to show the link
* context.context.display_oai_pmh_item_links - places the block
Note that, All Repository Content OAI-PMH set did not include collection items.  I kept it that way.  Thus, these links don't show for collection items.
> oai-pmh mods representation (attempt 2)

- config/sync/context.context.display_oai_pmh_item_links.yml
- config/sync/rdf.mapping.node.islandora_object.yml
Further to the OAI-PMH links being shown, 
* don't show the block title as "OAI-PMH Item Links" is very user-unfriendly.
* Map typed relation to a DC predicate in the RDF mapping, which means it will be found by OAI-PMH (which for DC only looks at the RDF mappings which are DC elements or DC terms.). This causes some duplication in the JSONLD mapping, as any linked agents (such as author and publisher) will be shown both as dc:contributor's and with their respective relators predicates.
Is this desirable?
> Don't show block title, and map linked agent to DC.

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/system.action.image_generate_a_thumbnail_from_an_original_file.yml
- config/sync/views.view.solr_search_content.yml
- config/sync/views.view.thumbnail.yml
- config/sync/views.view.thumbnail_of_first_child.yml
- config/sync/views_field_view.settings.yml
[Draft PR]
* Create a View (Block display) to display an object's thumbnail. You can now place this block and pass it a contextual filter (or give it the content id in the url) and it'll render the thumbnail.
* Create another view that finds the thumbnail of the first child. This will be used as a fallback (need demo content to test it
* use the thumbnail in the top level collection view
* use the thumbnail in search api solr view - WARNING - does not go well with the Grid display.
* Makes our islandora thumbnail action use 220x220 to match drupal's medium image style.
> Add thumbnail view and view with fallback.

- config/sync/field.storage.media.field_media_image.yml
Changed configuration file for image storage to use Fedora instead of public.
Related issue: https://github.com/Islandora-Devops/islandora-starter-site/issues/78
> Changing uri scheme from public to Fedora

- config/sync/user.role.anonymous.yml
- config/sync/user.role.authenticated.yml
Changes the configuration for anonymous and authenticated users to be able to view MODS and DC records for repository objects.
Related issue: https://github.com/Islandora-Devops/islandora-starter-site/issues/79
> OAI-PMH access for anonymous and authenticated users

- config/sync/views.view.missing_media.yml
This pr changes the missing media view configuration file. I've added csv data exports for all of the media types checked for missing media. I've included the pid and content id fields for each media type view. I've added generate derivative actions to the media type views that are missing derivatives that are generated.
To Test:
Make a fresh starter site using this pr.
Add repository items and media.
Delete some of the media.
Choose the missing media view that makes sense for the media you deleted.
Select one or more models and click apply.
Download the csv.
Select one or more rows to perform derivative generation on and click apply to selected items.
> Fixed data exports, added pid and id fields, added generate actions

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/views.view.content.yml
I had thought myself to be clever and created a single checkbox, "No parents", which filters the content to nodes with no parents. It causes a large number of error messages in the Watchdog logs, because the numeric filter was being loaded without a value. 
`Warning: Undefined array key "value" in Drupal\views\Plugin\views\filter\NumericFilter->acceptExposedInput() (line 426 of /var/www/html/drupal/web/core/modules/views/src/Plugin/views/filter/NumericFilter.php) `
This fixes it by making the "Number of Parents" filter similar to the "Number of Children" and "Number of Media" filters.
> Use a proper numeric filter for parents in Content view.

- README.md
- config/sync/migrate_plus.migration.islandora_defaults_tags.yml
- config/sync/migrate_plus.migration.islandora_tags.yml
Ticket: https://github.com/Islandora/documentation/issues/2161
Related PR: https://github.com/Islandora/islandora_mirador/pull/21
This PR adds `islandora` as a tag for the two migrations that the Starter SIte contains. 
This allows us to call them all at once (along with islandora_fits_tags and islandora_mirador_tags if you have them installed). 
I also updated the README, which had contradictory instructions and example. It now instructs and shows migrating using the `--tag` option.
> Migration tags

- composer.lock
Stomp was causing the following error messages on php 8.1:
`Deprecated function: Return type of Stomp\Transport\Frame::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 19 of /var/www/html/drupal/vendor/stomp-php/stomp-php/src/Transport/Frame.php) `
The recent release of Stomp corrects this. Luckily, this version still allows us to be compatible with php 7.4.
> Update Stomp and other deps.

- README.md
With https://github.com/Islandora-Devops/islandora-starter-site/pull/90 being merged, we no longer have the documented patch in place, so let's remove the reference to it.
> Remove reference to `rest_oai_pmh` patch that is no longer applied/relevant

- config/sync/block.block.memberofswc.yml
Ticket: https://github.com/LEAF-VRE/islandora-UX-useathon/issues/12
This hides the block that shows the "Member of" facet on collection search because it is mostly redundant.
A use case for this facet would be many nested collections, but right now its presence - especially with the demo content - is more useless than useful so this PR hides the block (without removing the facet altogether in case someone wants to use it for their data).
> Disable Member Of facet on collection search.

- config/sync/field.field.node.islandora_object.field_linked_agent.yml
As discussed at the MIG meeting, August 28 2023;
Per: https://github.com/LEAF-VRE/islandora-UX-useathon/issues/14
We had more-or-less consensus that "Contributors" would be broad enough to cover this and be understandable by lay people as well as metadata professionals.
We will also mention in the release notes that this can be changed at will for your own site, and that it is one setting that applies to all objects regardless of collections.
> Rename "Linked Agent" to "Contributors"

- config/sync/views.view.oai_pmh.yml
Without a pager on Views used by REST OAI-PMH, the resulting OAI endpoint will only have the first page of results in its output. This PR changes the default OAI-PMH Views to use a pager.
[Relevant slack conversation](https://islandora.slack.com/archives/C019U12D44Q/p1698177427211869?thread_ts=1698169612.926019&cid=C019U12D44Q)
> Use a pager on OAI views

- config/sync/views.settings.yml
Opening the advanced tab in Views all the time is annoying and in managing an Islandora, you often need to do advanced views magic. This enables the setting to have the Advanced tab open by default. I often forget the option is there.
> Open advanced Views tab by default.

- config/sync/field.field.node.islandora_object.field_linked_agent.yml
Staci Ross (@str51) pointed out in the [MIG](https://github.com/islandora-interest-groups/Islandora-Metadata-Interest-Group/blob/main/Meetings/2024/2024-01-29.md) that we made an error in assigning `relators:asn` as the default linked agent relator. That term, "Associated name", has to do with item provenance (where more specific terms "Former owner", "Donor", etc. do not apply). 
Source: https://www.loc.gov/marc/relators/relaterm.html
What we intended, and what this PR provides, is to use `relators:att` or "Attributed Name" which is about attributing authorship/creatorship etc.
This PR switches out the former for the latter as the "no entry selected" top of the list in the Contributors field drop-down.
> Fix the default relator in the Contributors (Linked Agent) field.

- config/sync/views.view.oai_pmh.yml
Slack conversations:
* https://islandora.slack.com/archives/CM5PPAV28/p1706896206520609
* https://islandora.slack.com/archives/C019U12D44Q/p1707321300893149
It was found that the OAI view of MODS breaks (shows `<error code="idDoesNotExist">The value of the identifier argument is unknown or illegal in this repository.</error>`) if the object's model has no external uri. This can happen if creating custom models.
The view clearly was not meant to exclude objects with null external URI in their Model. After testing, it seems that a views filter of "value is not equal to some-string" also excludes rows where the value does not exist.
This PR adds a grouped filter so it tests if Model's external URI (is null or is not equal to `http://purl.org/dc/dcmitype/Collection`).
> Add grouped filter to accommodate null external uris in model.

- composer.json
- composer.lock
- config/sync/block.block.creatorsandcontributors.yml
- config/sync/block.block.creatorsandcontributors_swc.yml
- config/sync/block.block.memberof.yml
- config/sync/block.block.memberofswc.yml
- config/sync/block.block.physicalform.yml
- config/sync/block.block.physicalformswc.yml
- config/sync/block.block.resource_type_swc.yml
- config/sync/block.block.resourcetype.yml
- config/sync/block.block.search.yml
- config/sync/block.block.solrsearchcontentadvancedsearchforblock.yml
- config/sync/block.block.solrsearchcontentadvancedsearchforpage.yml
- config/sync/block.block.solrsearchcontentsearchresultspagerforblock.yml
- config/sync/block.block.solrsearchcontentsearchresultspagerforpage.yml
- config/sync/block.block.subject.yml
- config/sync/block.block.subjectname.yml
- config/sync/block.block.subjectnamesswc.yml
- config/sync/block.block.subjectsswc.yml
- config/sync/block.block.subjecttemporalswc.yml
- config/sync/block.block.temporalsubject.yml
- config/sync/block.block.views_block__solr_search_content_block_1.yml
- config/sync/block.block.year.yml
- config/sync/block.block.yearswc.yml
- config/sync/core.extension.yml
Yesterday at the LAC-GLAM interest group, Jess Colati pointed out there's a module that lets you control, rather than be overwhelmed by, the permissions matrix. It adds a module filter-like UI with different tabs per module, as well as the ability to narrow down the roles you want to see and filter by whether those permissions are granted or not granted to those roles.
This PR adds the module.
My config export (on a brand new clean starter site) also included a bunch of removals of `context` and `context_all` blocks from the `visibility` sections of blocks. This looks perfectly innocuous to me, because they have no values.
> Add the "Fast Permissions Administration" (`fpa`) module.

- config/sync/core.entity_view_display.media.image.thumbnail.yml
This is a "quick fix" regarding a discussion in Slack regarding broken thumbnails caused by Drupal trying to create "Image Style" derivatives in the fedora flysystem when browsing as anonymous.
This "fix" shows thumbnail images at their original size. A [paired PR](https://github.com/Islandora-Devops/islandora_demo_objects/pull/9) resizes the Demo objects' thumbnails to be the same height (220x220) as the "medium" image style removed here.
If you are using the starter site, be aware that you should make your thumbnails "thumbnail sized". (if you use Fedora at all. Or, see below)
A better fix is for the Fedora Flysystem adapter to declare Fedora as non-writable when browsing as anonymous. Then image style derivatives should be created in public://. See issue: …
> Change the thumbnail display for image media to not use image styles.

- config/sync/core.entity_form_display.node.islandora_object.default.yml
Because the default form is so long and it's hard to find anything, I have proposed this "collapsible form". This is a new layout for the default Repository Item form, and it puts all the fields (except Model, which is required, and at the top) into collapsible "Details" sections, and all of them (except Title And Contributors) are collapsed by default. The result is a smaller form where it is easier to get to the bottom, and hopefully easier too to find individual elements.
This has gone through the Metadata Interest Group for revision and feedback. Some, unfortunately not implemented, include:
* can we get buttons to "Expand All" / "Collapse All" ? (No, can't find any way to do this)
* can we style each field label to look the same? Currently they're only shaded/big/prominent if the …
> Give Repository Item a sectioned, collapsible form.

- composer.json
- composer.lock
- config/sync/core.entity_view_display.node.article.default.yml
- config/sync/core.entity_view_display.node.article.rss.yml
- config/sync/core.entity_view_display.node.article.teaser.yml
- config/sync/core.entity_view_display.node.islandora_object.default.yml
- config/sync/core.entity_view_display.node.islandora_object.search_index.yml
- config/sync/core.entity_view_display.node.islandora_object.search_result.yml
- config/sync/core.entity_view_display.node.islandora_object.teaser.yml
- config/sync/core.entity_view_display.node.page.default.yml
- config/sync/core.entity_view_display.node.page.teaser.yml
- config/sync/core.extension.yml
- config/sync/field.field.node.islandora_object.field_linked_agent.yml
- config/sync/views.view.solr_search_content.yml
- config/sync/views.view.thumbnail.yml
- config/sync/views.view.thumbnail_of_first_child.yml
- config/sync/views.view.top_level_collections.yml
Added and enabled Discovery Garden's dgi image discovery module. Changed the solr and top level collections views to use this module for the thumbnail field instead of the thumbnail views. The thumbnail views were then disabled.
To test, add repository content with thumbnails that can be searched and has at least one collection and check if the thumbnails display in the search and the top level collections views.
> Add image discovery module

- config/sync/field.field.node.islandora_object.field_subject.yml
Other Subject fields which get terms from a single vocabulary allow users to create new terms on the fly. This brings Subject - Topical (field_subject) in line with those.
> Allow Subject - Topical to create new terms.

- composer.json
- composer.lock
- config/sync/islandora_mirador.settings.yml
Updates to the above listed components and their dependencies.
There is also an update to Mirador settings because apparently we didn't set the Mirador plugins when they became available. This enables them.
* Citation Select causes slews of errors to the watchdog logs, but it did on the current version too so I thought that should not prevent us from updating. There is [at least one ticket open](https://github.com/digitalutsc/citation_select/issues/19) in that repo.
* Flysystem was tested by adding files to Fedora, which worked. 
Still to add/test updates to:
* Filehash ([composer locked to 2.x in Islandora core](https://github.com/Islandora/islandora/issues/1005))
* Geolocation Field
* Facets (requires Solr; my solr instance is broken and there is an outstanding ticket to update it in …
> Updates to Drupal, BibCite, Citation Select, and Flysystem

- config/sync/context.context.mirador_block_multipaged_items.yml
- config/sync/islandora_iiif.settings.yml
Changes the book manifest to pull service files instead of tiffs.  It's much faster.
Also added a default title for the Mirador viewer.
> Updated IIIF configs

- config/sync/views.view.oai_pmh_item_data.yml
- config/sync/views.view.solr_search_content.yml
We fell victim to [this bug](https://www.drupal.org/project/search_api/issues/3437379), after not thoroughly testing after running a database update. 
This PR fixes our views by using an actual caching value.
@aOelschlager for finding it.
> Use a real cache option.

- composer.lock
- config/sync/search_api.index.default_solr_index.yml
Controlled_access_terms: the solr processor settings are [of a new format](https://github.com/Islandora/controlled_access_terms/blob/9c9a3f6b4c0ea2d9598092aa232a470d684f9786/src/Plugin/search_api/processor/EDTFYear.php#L142)
Without the settings changes to the new format, this will cause the processor to break and/or emit errors
https://github.com/Islandora/controlled_access_terms/pull/113
https://github.com/Islandora/controlled_access_terms/pull/114
https://islandora.slack.com/archives/CM5PPAV28/p1712939510602939
https://github.com/Islandora/controlled_access_terms/issues/117
> Fix EDTF Year processor settings

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/pathauto.pattern.repository_items.yml
- config/sync/pathauto.settings.yml
- config/sync/system.action.pathauto_update_alias_node.yml
- config/sync/system.action.pathauto_update_alias_user.yml
> Enable Pathauto and configure a title-based alias.

- config/sync/context.context.default_media_display.yml
- config/sync/context.context.mirador_block_single_image_items.yml
- config/sync/core.entity_view_display.media.file.mirador.yml
- config/sync/core.entity_view_display.media.image.mirador.yml
- config/sync/core.entity_view_mode.media.mirador.yml
This set of configs (thank you Mark!) sets up a context and view mode so that single paged items can be viewed in Mirador by selecting the "Viewer Override" of "Mirador".
Note that this does NOT import the "Mirador" taxonomy term as that is already done by the Islandora Mirador module in a migration that is tagged `islandora` and is therefore run during provisioning of ISLE-DC and (as of today) the Site Template.
To test:
With this PR, create an Image or Page object and set its Viewer Override to "Mirador".
Add a Service File (either by adding an Original File (Tiff or JP2 as File, or jpg/png/gif as Image) that makes derivatives, or directly). Results: The service file should display in the Mirador viewer on the node object's page.
> Add "Single Page Mirador Viewer" functionality, on par with OpenSeadragon.

- config/sync/core.entity_form_display.media.audio.media_library.yml
- config/sync/core.entity_form_display.media.document.media_library.yml
- config/sync/core.entity_form_display.media.extracted_text.media_library.yml
- config/sync/core.entity_form_display.media.file.media_library.yml
- config/sync/core.entity_form_display.media.fits_technical_metadata.media_library.yml
- config/sync/core.entity_form_display.media.image.media_library.yml
- config/sync/core.entity_form_display.media.remote_video.media_library.yml
- config/sync/core.entity_form_display.media.video.media_library.yml
- config/sync/core.entity_form_display.node.islandora_object.default.yml
- config/sync/core.entity_form_mode.media.media_library.yml
- config/sync/core.entity_view_display.media.audio.media_library.yml
- config/sync/core.entity_view_display.media.document.media_library.yml
- config/sync/core.entity_view_display.media.extracted_text.media_library.yml
- config/sync/core.entity_view_display.media.file.media_library.yml
- config/sync/core.entity_view_display.media.fits_technical_metadata.media_library.yml
- config/sync/core.entity_view_display.media.image.media_library.yml
- config/sync/core.entity_view_display.media.remote_video.media_library.yml
- config/sync/core.entity_view_display.media.video.media_library.yml
- config/sync/core.entity_view_display.node.islandora_object.default.yml
- config/sync/core.entity_view_display.node.islandora_object.search_index.yml
- config/sync/core.entity_view_display.node.islandora_object.search_result.yml
- config/sync/core.entity_view_display.node.islandora_object.teaser.yml
- config/sync/core.entity_view_mode.media.media_library.yml
- config/sync/core.extension.yml
- config/sync/field.field.node.islandora_object.field_representative_image.yml
- config/sync/field.storage.node.field_representative_image.yml
- config/sync/image.style.media_library.yml
- config/sync/media_library.settings.yml
- config/sync/views.view.media_library.yml
This pull request 
* enables the core Media Library plugin.
* Creates a new field called "Representative Image" on Repository Item and explains its use in the DGI Discovered Image module.
> Add Representative Image field and Media library.

- config/sync/user.settings.yml
Change the user settings so only admin can create accounts, instead of visitors being able to request accounts.
I've had a few account requests on my production sites which are most likely bots trying to find security holes.
> change so only admin can create accounts

- config/sync/admin_toolbar_search.settings.yml
- config/sync/admin_toolbar_tools.settings.yml
- config/sync/core.extension.yml
As suggested by Rebel, I enabled Admin Toolbar Extras. This makes the dropdown menus behave more like they did in the ~Site Template~ Install Profile. For one, you can go to Content > Add Content > Repository Item just in the dropdown menus. You can also access Structure > Block Types.
> Add Admin Toolbar Extras.

- composer.json
- composer.lock
islandora/islandora_mirador should now use drupal namespace. islandora/islandora was removed because drupal/islandora was already there.
This still leaves islandora/views_nested_details as the last remaining islandora namespace, but it looks like it's not been updated to the drupal namespace yet. Possibly because it's owned by Islandora Labs? https://github.com/Islandora-Labs/views_nested_details
> Update composer.json to use drupal instead of islandora namespace

- .github/workflows/ci.yml
- composer.json
- composer.lock
I accidentally deleted the active branch of the PR for #155 . 
This is the second try!
> Drush 13, second attempt

- config/sync/search_api.index.default_solr_index.yml
Set the solr index tracker at `/admin/config/search/search-api/index/default_solr_index/edit` to `Index parallel` instead of `Default`. This allows the parallel solr index drush command to run with multiple threads. e.g.
```
$ drush search-api-solr:index-parallel default_solr_index \
--threads=5 \
--batch-size=100 \
--uri=https://islandora.dev
```
This can significantly speed up solr re-indexing for sites with a lot of content, so it's a good base to start with. Switching the tracker from `Default -> Index parallel` after content is added causes drupal/search_api_solr to re-run the tracking on all your content; only a one time inconvenience, but still best to be avoided.
Without this PR this command only runs with a single thread
```
$ drush search-api-solr:index-parallel …
```
> Use parallel index tracker for solr

- composer.json
- composer.lock
- renovate.json5
We're a few major versions behind the current https://github.com/mozilla/pdf.js release. This PR gets us up-to-date and also configures renovate to start detecting updates for this library and issuing PRs when updates are found.
> Upgrade pdf.js from 2.x -> 5.x and have renovate track updates

- renovate.json5
With https://github.com/renovatebot/renovate/pull/36902 merged our composer updates can now bring in dependencies by enabling the composer `-W` flag with the new [`postUpdate`](https://docs.renovatebot.com/configuration-options/#postupdateoptions) option
> Have renovate run composer update -W
